#!/usr/bin/env python3
"""Expand Knowledge word dicts from SAFTI booklist / SSQ FinTech / OOMWOO notes."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAIN = ROOT / "public/dicts/knowledge-from-articles.json"
FT_OUT = ROOT / "public/dicts/knowledge-fintech-core.json"
CS_OUT = ROOT / "public/dicts/knowledge-cs-core.json"
ROBOT_OUT = ROOT / "public/dicts/knowledge-robotics-ros2.json"
SSQ_OUT = ROOT / "public/dicts/knowledge-ssq-fintech-start.json"


def save(path: Path, data: list[dict]) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def filter_by_keywords(words: list[dict], keys: list[str], limit: int) -> list[dict]:
    out: list[dict] = []
    for w in words:
        n = w["name"].lower()
        if any(k in n for k in keys):
            out.append(w)
        if len(out) >= limit:
            break
    return out


FINTECH_EXTRA: list[tuple[str, str]] = [
    ("Mankiw", "曼昆（经济学原理）"),
    ("Mishkin", "米什金（货币金融学）"),
    ("Bodie", "博迪（投资学）"),
    ("Hull", "赫尔（期权期货）"),
    ("Taleb", "塔勒布（黑天鹅）"),
    ("Kahneman", "卡尼曼（思考快与慢）"),
    ("Shiller", "席勒（非理性繁荣）"),
    ("Munger", "芒格（穷查理宝典）"),
    ("Black-Scholes", "布莱克-舒尔斯模型"),
    ("black swan", "黑天鹅事件"),
    ("fat tail", "肥尾分布"),
    ("skewness", "偏度"),
    ("kurtosis", "峰度"),
    ("cumulant", "累积量"),
    ("regime", "市场状态；体制"),
    ("regime switching", "状态切换模型"),
    ("GMM", "高斯混合模型"),
    ("Markov chain", "马尔可夫链"),
    ("transition matrix", "转移矩阵"),
    ("stationary distribution", "稳态分布"),
    ("steady state", "稳态"),
    ("ergodic", "遍历的"),
    ("absorbing state", "吸收态"),
    ("feedback loop", "反馈回路"),
    ("house edge", "庄家优势"),
    ("odds", "赔率"),
    ("expected payoff", "期望收益"),
    ("lottery", "彩票"),
    ("jackpot", "头奖"),
    ("prize pool", "奖池"),
    ("ticket sales", "投注额"),
    ("frequency analysis", "频次分析"),
    ("chi-square test", "卡方检验"),
    ("goodness of fit", "拟合优度"),
    ("uniform distribution", "均匀分布"),
    ("independence test", "独立性检验"),
    ("crawler", "爬虫"),
    ("scraper", "抓取器"),
    ("feature vector", "特征向量"),
    ("precompute", "预计算"),
    ("scheduler", "调度器"),
    ("APScheduler", "Python 定时调度库"),
    ("Flask", "Flask Web 框架"),
    ("SQLite", "SQLite 数据库"),
    ("validator", "验证器"),
    ("bidirectional validation", "双向验证"),
    ("genetic algorithm", "遗传算法"),
    ("candidate sampling", "候选采样"),
    ("cost function", "代价函数"),
    ("scoring", "打分"),
    ("orchestration", "编排"),
    ("data hub", "数据中枢"),
    ("bettor behavior", "投注者行为"),
    ("bounded rationality", "有限理性"),
    ("gambler fallacy", "赌徒谬误"),
    ("hot hand fallacy", "热手谬误"),
    ("availability heuristic", "可得性启发"),
    ("representativeness heuristic", "代表性启发"),
    ("system 1", "系统1快思考"),
    ("system 2", "系统2慢思考"),
    ("irrational exuberance", "非理性繁荣"),
    ("animal spirits", "动物精神"),
    ("random walk theory", "随机游走理论"),
    ("skin in the game", "利益攸关"),
    ("mental model", "心智模型"),
    ("circle of competence", "能力圈"),
    ("margin of safety", "安全边际"),
    ("money supply", "货币供给"),
    ("money demand", "货币需求"),
    ("fractional reserve", "部分准备金"),
    ("bank run", "银行挤兑"),
    ("lender of last resort", "最后贷款人"),
    ("financial intermediation", "金融中介"),
    ("asymmetric payoff", "不对称收益"),
    ("optionality", "期权性"),
    ("convex payoff", "凸性收益"),
    ("tail risk", "尾部风险"),
    ("left tail", "左尾"),
    ("right tail", "右尾"),
    ("prize structure", "奖金结构"),
    ("payout ratio", "派彩比率"),
    ("bookmaker", "庄家"),
    ("inventory risk", "库存风险"),
    ("model risk", "模型风险"),
    ("data leakage", "数据泄漏"),
    ("look-ahead bias", "前视偏差"),
    ("survivorship bias", "幸存者偏差"),
    ("walk-forward", "前向滚动验证"),
    ("out of sample", "样本外"),
    ("in sample", "样本内"),
    ("transition probability", "转移概率"),
    ("state space", "状态空间"),
    ("latent variable", "潜变量"),
    ("mixture model", "混合模型"),
    ("EM algorithm", "期望最大化算法"),
    ("log likelihood", "对数似然"),
    ("Bayesian update", "贝叶斯更新"),
    ("dynamical system", "动力系统"),
    ("entropy", "熵"),
    ("mutual information", "互信息"),
    ("spurious correlation", "伪相关"),
    ("p-hacking", "p值操纵"),
    ("reproducibility", "可复现性"),
    ("annotated code", "注解代码"),
    ("time preference", "时间偏好"),
    ("liquidity preference", "流动性偏好"),
    ("Fisher effect", "费雪效应"),
    ("quantity theory of money", "货币数量论"),
    ("velocity of money", "货币流通速度"),
    ("term structure", "期限结构"),
    ("forward rate", "远期利率"),
    ("spot rate", "即期利率"),
    ("par yield", "平价收益率"),
    ("dirty price", "含息全价"),
    ("clean price", "净价"),
    ("accrued interest", "应计利息"),
    ("day count convention", "计日惯例"),
    ("put-call parity", "看跌看涨平价"),
    ("implied volatility", "隐含波动率"),
    ("historical volatility", "历史波动率"),
    ("Greeks", "期权希腊字母"),
    ("delta hedging", "德尔塔对冲"),
    ("gamma", "伽马"),
    ("vega", "维加"),
    ("theta", "西塔时间损耗"),
    ("American option", "美式期权"),
    ("European option", "欧式期权"),
    ("early exercise", "提前行权"),
    ("binomial tree", "二叉树定价"),
    ("risk-neutral", "风险中性"),
    ("no-arbitrage", "无套利"),
    ("replicating portfolio", "复制组合"),
    ("complete market", "完全市场"),
    ("incomplete market", "不完全市场"),
    ("utility maximization", "效用最大化"),
    ("indifference curve", "无差异曲线"),
    ("budget constraint", "预算约束"),
    ("consumer surplus", "消费者剩余"),
    ("producer surplus", "生产者剩余"),
    ("deadweight loss", "无谓损失"),
    ("externality", "外部性"),
    ("public good", "公共物品"),
    ("free rider", "搭便车"),
    ("comparative advantage", "比较优势"),
    ("absolute advantage", "绝对优势"),
    ("purchasing power parity", "购买力平价"),
    ("interest rate parity", "利率平价"),
    ("carry trade", "套息交易"),
    ("flight to quality", "避险追逐质量"),
    ("credit crunch", "信贷紧缩"),
    ("macroprudential", "宏观审慎"),
    ("microprudential", "微观审慎"),
    ("house model", "庄家模型"),
    ("feedback mechanism", "反馈机制"),
    ("predictability", "可预测性"),
    ("unpredictable", "不可预测的"),
    ("production system", "生产系统"),
    ("analysis script", "分析脚本"),
    ("web service", "Web 服务"),
    ("configuration", "配置"),
    ("traceback", "堆栈追踪"),
    ("logging", "日志"),
    ("soft assignment", "软分配"),
    ("hard assignment", "硬分配"),
    ("observation", "观测值"),
    ("state vector", "状态向量"),
    ("market heat", "市场热度"),
    ("prize feedback", "奖池反馈"),
    ("betting volume", "投注量"),
    ("jackpot rollover", "奖池滚存"),
    ("independent draw", "独立开奖"),
    ("kernel module", "核心模块"),
    ("label leakage", "标签泄漏"),
    ("offline analysis", "离线分析"),
    ("online service", "在线服务"),
    ("batch pipeline", "批处理流水线"),
    ("daily job", "日批任务"),
    ("course linkage", "课程联动"),
    ("probability modeling", "概率建模"),
    ("software engineering", "软件工程"),
    ("data engineering", "数据工程"),
    ("product thinking", "产品思维"),
    ("FinTech starter", "FinTech 起步项目"),
    ("ssq predictor", "双色球预测系统"),
    ("dual validator", "双向验证器"),
    ("transfer matrix", "转移矩阵（同 transition）"),
    ("market regime", "市场 Regime"),
    ("number frequency", "号码频次"),
    ("distribution test", "分布检验"),
    ("scraping pipeline", "抓取流水线"),
    ("JSON dataset", "JSON 数据集"),
    ("feature precompute", "特征预计算"),
    ("service oriented", "面向服务"),
    ("monolith script", "单体脚本"),
]

CS_EXTRA: list[tuple[str, str]] = [
    ("ROS2", "机器人操作系统第二代"),
    ("ROS", "机器人操作系统"),
    ("Nav2", "ROS2 导航栈"),
    ("SLAM", "同步定位与地图构建"),
    ("LiDAR", "激光雷达"),
    ("2D LiDAR", "二维激光雷达"),
    ("Gazebo", "机器人仿真环境"),
    ("URDF", "统一机器人描述格式"),
    ("Xacro", "URDF 宏语言"),
    ("tf2", "ROS 坐标变换库"),
    ("base_link", "机器人基坐标系"),
    ("odometry", "里程计"),
    ("localization", "定位"),
    ("mapping", "建图"),
    ("navigation", "导航"),
    ("path planning", "路径规划"),
    ("global planner", "全局规划器"),
    ("local planner", "局部规划器"),
    ("costmap", "代价地图"),
    ("occupancy grid", "占用栅格地图"),
    ("point cloud", "点云"),
    ("laser scan", "激光扫描"),
    ("RViz", "ROS 可视化"),
    ("rclpy", "ROS2 Python 客户端"),
    ("rclcpp", "ROS2 C++ 客户端"),
    ("publisher", "发布者"),
    ("subscriber", "订阅者"),
    ("QoS", "通信服务质量"),
    ("lifecycle node", "生命周期节点"),
    ("launch file", "启动文件"),
    ("colcon", "ROS2 构建工具"),
    ("ament", "ROS2 构建系统"),
    ("micro-ROS", "微控制器 ROS"),
    ("ESP32", "ESP32 微控制器"),
    ("Arduino", "Arduino 平台"),
    ("Raspberry Pi", "树莓派"),
    ("Home Assistant", "开源智能家居平台"),
    ("firmware", "固件"),
    ("PCB", "印刷电路板"),
    ("BOM", "物料清单"),
    ("3D printing", "3D 打印"),
    ("FDM", "熔融沉积成型"),
    ("chassis", "底盘"),
    ("wheelbase", "轴距"),
    ("differential drive", "差速驱动"),
    ("motor driver", "电机驱动"),
    ("encoder", "编码器"),
    ("IMU", "惯性测量单元"),
    ("bumper", "防撞条"),
    ("suction fan", "吸尘风机"),
    ("dust bin", "尘盒"),
    ("docking", "回充对接"),
    ("bringup", "整机联调"),
    ("simulation-first", "仿真优先"),
    ("hardware-in-the-loop", "硬件在环"),
    ("interface contract", "接口契约"),
    ("module boundary", "模块边界"),
    ("RFC", "设计提案"),
    ("REP-103", "ROS 坐标约定"),
    ("right-handed frame", "右手坐标系"),
    ("radian", "弧度"),
    ("SI units", "国际单位制"),
    ("safety review", "安全评审"),
    ("power budget", "功率预算"),
    ("mass budget", "质量预算"),
    ("bounding envelope", "包络尺寸"),
    ("mounting pattern", "安装孔位"),
    ("open source", "开源"),
    ("Apache-2.0", "Apache 2.0 许可"),
    ("vendor lock-in", "厂商锁定"),
    ("local-first", "本地优先"),
    ("telemetry", "遥测"),
    ("watchdog", "看门狗"),
    ("recovery behavior", "恢复行为"),
    ("obstacle avoidance", "避障"),
    ("coverage path planning", "覆盖路径规划"),
    ("cleaning job", "清扫任务"),
    ("calibration", "标定"),
    ("sensor fusion", "传感器融合"),
    ("state estimation", "状态估计"),
    ("PID control", "PID 控制"),
    ("control loop", "控制回路"),
    ("real-time", "实时"),
    ("embedded system", "嵌入式系统"),
    ("GPIO", "通用输入输出"),
    ("I2C", "I2C 总线"),
    ("SPI", "SPI 总线"),
    ("UART", "串口"),
    ("PWM", "脉宽调制"),
    ("battery management", "电池管理"),
    ("charging cycle", "充电循环"),
    ("brownout", "欠压"),
    ("thermal protection", "过热保护"),
    ("digital twin", "数字孪生"),
    ("hackable", "可改装"),
    ("pull request", "拉取请求"),
    ("maintainer", "维护者"),
    ("integration test", "集成测试"),
    ("smoke test", "冒烟测试"),
    ("reproducible build", "可复现构建"),
    ("MVP", "最小可行产品"),
    ("stretch goal", "延伸目标"),
    ("bill of materials", "物料清单"),
    ("teardown", "拆机分析"),
    ("reference design", "参考设计"),
    ("swappable module", "可替换模块"),
    ("thread safety", "线程安全"),
    ("executor", "ROS2 执行器"),
    ("callback group", "回调组"),
    ("remapping", "重映射"),
    ("rosbag", "ROS 录包"),
    ("replay", "回放"),
    ("profiling", "性能剖析"),
    ("bottleneck", "瓶颈"),
    ("jitter", "抖动"),
    ("best effort", "尽力而为 QoS"),
    ("reliable QoS", "可靠 QoS"),
    ("history depth", "历史深度"),
    ("namespace", "命名空间"),
    ("composition", "组件组合"),
    ("parameter", "参数"),
    ("dependency pinning", "依赖钉死"),
    ("Docker", "Docker 容器"),
    ("CI pipeline", "CI 流水线"),
    ("architecture decision record", "架构决策记录"),
    ("north star metric", "北极星指标"),
    ("collision avoidance", "防碰撞"),
    ("drive wheel", "驱动轮"),
    ("brush motor", "边刷电机"),
    ("I/O board", "IO 电路板"),
    ("firmware update", "固件更新"),
    ("over-the-air", "空中升级"),
    ("local control", "本地控制"),
    ("cloud optional", "云可选"),
    ("Gazebo plugin", "Gazebo 插件"),
    ("URDF joint", "URDF 关节"),
    ("inertia", "惯性"),
    ("friction", "摩擦"),
    ("torque", "力矩"),
    ("angular velocity", "角速度"),
    ("linear velocity", "线速度"),
    ("pose", "位姿"),
    ("transform", "变换"),
    ("frame_id", "坐标系 id"),
    ("child frame", "子坐标系"),
    ("parent frame", "父坐标系"),
    ("static transform", "静态变换"),
    ("dynamic transform", "动态变换"),
    ("map frame", "地图坐标系"),
    ("odom frame", "里程计坐标系"),
    ("AMCL", "自适应蒙特卡洛定位"),
    ("slam_toolbox", "SLAM 工具箱"),
    ("behavior tree", "行为树"),
    ("bt navigator", "行为树导航"),
    ("spin recovery", "旋转恢复"),
    ("backup recovery", "后退恢复"),
    ("wait recovery", "等待恢复"),
    ("goal pose", "目标位姿"),
    ("waypoint", "航点"),
    ("path follower", "路径跟随"),
    ("controller server", "控制器服务"),
    ("planner server", "规划器服务"),
    ("smoother", "平滑器"),
    ("footprint", "足迹轮廓"),
    ("inflation radius", "膨胀半径"),
    ("lethal cost", "致命代价"),
    ("unknown space", "未知空间"),
    ("free space", "自由空间"),
    ("occupied space", "占用空间"),
    ("OOMWOO", "开源扫地机器项目"),
    ("makerspet", "OOMWOO 社区组织"),
    ("community module", "社区模块"),
    ("parallel contribution", "并行贡献"),
    ("interface specification", "接口规格"),
    ("simulation world", "仿真世界"),
    ("robot description", "机器人描述包"),
    ("bringup launch", "联调启动文件"),
    ("safety interlock", "安全互锁"),
    ("estop", "急停"),
    ("current limit", "限流"),
    ("voltage monitor", "电压监测"),
    ("watchdog timeout", "看门狗超时"),
    ("heartbeat", "心跳包"),
    ("health check", "健康检查"),
    ("graceful shutdown", "优雅停机"),
    ("fault isolation", "故障隔离"),
    ("degraded mode", "降级模式"),
    ("fail-safe", "失效安全"),
    ("fail-soft", "失效软化"),
    ("race condition", "竞态条件"),
    ("deadlock", "死锁"),
    ("mutex", "互斥锁"),
    ("lock-free", "无锁"),
    ("message queue", "消息队列"),
    ("event loop", "事件循环"),
    ("polling", "轮询"),
    ("interrupt", "中断"),
    ("DMA", "直接内存访问"),
    ("baud rate", "波特率"),
    ("CRC", "循环冗余校验"),
    ("checksum", "校验和"),
    ("packet loss", "丢包"),
    ("retransmission", "重传"),
    ("latency budget", "延迟预算"),
    ("bandwidth", "带宽"),
    ("backpressure", "背压"),
    ("rate limit", "限流"),
    ("circuit breaker", "熔断器"),
    ("retry policy", "重试策略"),
    ("exponential backoff", "指数退避"),
    ("idempotent", "幂等"),
    ("exactly once", "精确一次"),
    ("at least once", "至少一次"),
    ("at most once", "至多一次"),
]


def main() -> None:
    words: list[dict] = json.loads(MAIN.read_text(encoding="utf-8"))
    seen = {w["name"].lower() for w in words}

    a1 = a2 = 0
    for name, trans in FINTECH_EXTRA:
        if name.lower() in seen:
            continue
        seen.add(name.lower())
        words.append({"name": name, "trans": [trans], "usphone": "", "ukphone": ""})
        a1 += 1
    for name, trans in CS_EXTRA:
        if name.lower() in seen:
            continue
        seen.add(name.lower())
        words.append({"name": name, "trans": [trans], "usphone": "", "ukphone": ""})
        a2 += 1

    save(MAIN, words)

    ft_keys = [
        "interest", "risk", "bond", "market", "credit", "capital", "portfolio", "option",
        "futures", "yield", "rate", "finance", "bank", "asset", "equity", "liability",
        "price", "return", "cash", "debt", "fund", "trade", "order", "margin", "leverage",
        "hedge", "swap", "curve", "inflation", "gdp", "monetary", "fiscal", "default",
        "premium", "liquidity", "volatil", "sharpe", "drawdown", "duration", "convex",
        "npv", "irr", "wacc", "dcf", "var", "capm", "ipo", "otc", "kyc", "aml", "esg",
        "defi", "block", "settlement", "clearing", "notional", "principal", "coupon",
        "maturity", "annuity", "dividend", "markov", "gmm", "regime", "lottery", "jackpot",
        "odds", "tail", "bias", "heuristic", "system 1", "system 2", "black swan", "fat tail",
        "arbitrage", "parity", "volatility", "greeks", "delta", "gamma", "vega", "theta",
        "house", "feedback", "transition", "stationary", "mixture", "em algorithm", "bayes",
        "walk-forward", "bookmaker", "payoff", "optionality", "taleb", "kahneman", "hull",
        "bodie", "mishkin", "mankiw", "shiller", "munger", "flask", "scheduler", "crawler",
        "validator", "scoring", "orchestration", "entropy", "mutual information", "prize",
        "ticket", "bettor", "gambler", "fisher", "term structure", "forward rate", "implied",
        "american option", "european option", "risk-neutral", "no-arbitrage", "utility",
        "surplus", "externality", "carry trade", "credit crunch", "macroprudential",
        "predictability", "production system", "analysis script", "web service", "logging",
        "latent", "state space", "chi-square", "frequency analysis", "goodness of fit",
        "skin in the game", "circle of competence", "margin of safety", "animal spirits",
        "irrational", "availability", "representativeness", "p-hacking", "spurious",
        "ssq", "dual validator", "fintech starter", "probability modeling", "data hub",
        "jackpot", "rollover", "independent draw", "soft assignment", "hard assignment",
        "black-scholes", "binomial tree", "replicating", "complete market", "put-call",
        "dirty price", "clean price", "accrued interest", "day count", "velocity of money",
        "quantity theory", "flight to quality", "microprudential", "macroprudential",
    ]
    cs_keys = [
        "ros", "nav2", "nav ", "slam", "lidar", "gazebo", "urdf", "tf2", "odom", "map frame",
        "planner", "costmap", "occupancy", "point cloud", "rviz", "rcl", "publisher",
        "subscriber", "qos", "launch", "colcon", "ament", "micro-ros", "esp32", "arduino",
        "raspberry", "home assistant", "firmware", "pcb", "bom", "3d print", "chassis",
        "motor", "encoder", "imu", "bumper", "suction", "dock", "bringup", "gpio", "i2c",
        "spi", "uart", "pwm", "pid", "sensor", "calibration", "fusion", "estimation",
        "recovery", "behavior", "footprint", "waypoint", "pose", "amcl", "executor",
        "callback", "rosbag", "docker", "ci pipeline", "mvp", "open source", "module boundary",
        "interface contract", "rfc", "safety", "watchdog", "telemetry", "embedded", "real-time",
        "function", "variable", "array", "async", "class", "algorithm", "sql", "api", "cache",
        "debug", "pipeline", "repository", "commit", "branch", "pandas", "numpy", "matrix",
        "vector", "probability", "distribution", "hash", "token", "mutex", "thread", "oomwoo",
        "navigation", "localization", "mapping", "simulation", "hardware", "laser",
        "path planning", "coverage", "obstacle", "state estimation", "control loop", "battery",
        "charging", "vendor", "local-first", "swappable", "teardown", "reference design",
        "bill of materials", "namespace", "remapping", "composition", "parameter", "jitter",
        "bottleneck", "profiling", "idempotent", "backoff", "circuit breaker", "rate limit",
        "backpressure", "checksum", "crc", "baud", "interrupt", "dma", "race condition",
        "deadlock", "free space", "occupied", "unknown space", "lethal", "goal pose",
        "path follower", "controller server", "planner server", "behavior tree", "spin recovery",
        "estop", "makerspet", "xacro", "frame_id", "child frame", "parent frame", "slam_toolbox",
        "cartographer", "bt navigator", "differential drive", "suction fan", "dust bin",
        "bringup launch", "fail-safe", "fail-soft", "heartbeat", "health check", "graceful",
        "degraded mode", "sim-first", "simulation-first", "digital twin", "hackable",
        "apache-2.0", "over-the-air", "i/o board", "drive wheel", "brush motor",
    ]

    fintech = filter_by_keywords(words, ft_keys, 220)
    cs = filter_by_keywords(words, cs_keys, 220)
    ssq = [
        w
        for w in words
        if any(
            k in w["name"].lower()
            for k in [
                "markov",
                "gmm",
                "regime",
                "lottery",
                "jackpot",
                "transition",
                "stationary",
                "feedback",
                "house",
                "odds",
                "crawler",
                "validator",
                "chi-square",
                "frequency",
                "mixture",
                "em algorithm",
                "walk-forward",
                "bettor",
                "gambler",
                "prize",
                "ticket",
                "scoring",
                "candidate",
                "genetic",
                "orchestration",
                "data hub",
                "flask",
                "apscheduler",
                "feature vector",
                "latent",
                "state space",
                "payoff",
                "bookmaker",
                "p-hacking",
                "look-ahead",
                "survivorship",
                "out of sample",
                "in sample",
                "reproducibility",
                "annotated",
                "fintech starter",
                "probability modeling",
                "soft assignment",
                "hard assignment",
                "expected payoff",
                "uniform distribution",
                "independence test",
                "goodness of fit",
                "precompute",
                "scheduler",
                "traceback",
                "logging",
                "predictability",
                "analysis script",
                "production system",
                "web service",
                "configuration",
                "ssq",
                "dual validator",
                "rollover",
                "independent draw",
                "cumulant",
                "skewness",
                "kurtosis",
                "fat tail",
                "black swan",
                "system 1",
                "system 2",
                "irrational exuberance",
                "scraping",
                "json dataset",
                "market heat",
                "number frequency",
                "distribution test",
            ]
        )
    ]
    robot = [
        w
        for w in words
        if any(
            k in w["name"].lower()
            for k in [
                "ros",
                "nav2",
                "slam",
                "lidar",
                "gazebo",
                "urdf",
                "tf2",
                "odom",
                "rviz",
                "rclpy",
                "rclcpp",
                "qos",
                "colcon",
                "ament",
                "micro-ros",
                "esp32",
                "arduino",
                "raspberry",
                "home assistant",
                "chassis",
                "motor",
                "encoder",
                "imu",
                "bumper",
                "suction",
                "dock",
                "bringup",
                "gpio",
                "i2c",
                "spi",
                "uart",
                "pwm",
                "pid",
                "costmap",
                "occupancy",
                "point cloud",
                "planner",
                "footprint",
                "waypoint",
                "pose",
                "amcl",
                "behavior tree",
                "recovery",
                "oomwoo",
                "firmware",
                "pcb",
                "bom",
                "3d print",
                "fdm",
                "watchdog",
                "telemetry",
                "embedded",
                "safety",
                "interface contract",
                "module boundary",
                "launch",
                "publisher",
                "subscriber",
                "rosbag",
                "executor",
                "callback",
                "map frame",
                "base_link",
                "differential drive",
                "coverage path",
                "obstacle",
                "sensor fusion",
                "state estimation",
                "reference design",
                "teardown",
                "bill of materials",
                "local-first",
                "vendor lock-in",
                "free space",
                "occupied space",
                "unknown space",
                "inflation radius",
                "lethal cost",
                "goal pose",
                "path follower",
                "controller server",
                "planner server",
                "spin recovery",
                "backup recovery",
                "wait recovery",
                "slam_toolbox",
                "makerspet",
                "estop",
                "fail-safe",
                "fail-soft",
                "heartbeat",
                "health check",
                "graceful shutdown",
                "degraded mode",
                "simulation-first",
                "digital twin",
                "hackable",
                "apache-2.0",
                "xacro",
                "frame_id",
                "child frame",
                "parent frame",
                "laser scan",
                "nav2",
                "path planning",
                "global planner",
                "local planner",
                "micro-ros",
                "home assistant",
                "over-the-air",
                "i/o board",
            ]
        )
    ]

    save(FT_OUT, fintech)
    save(CS_OUT, cs)
    save(SSQ_OUT, ssq)
    save(ROBOT_OUT, robot)

    print(f"main={len(words)} chapters≈{(len(words) + 19) // 20}")
    print(f"added fintech={a1} cs={a2}")
    print(f"fintech-core={len(fintech)} cs-core={len(cs)}")
    print(f"ssq-fintech={len(ssq)} robotics-ros2={len(robot)}")


if __name__ == "__main__":
    main()
